name: Set up ABQ
description: Installs the ABQ CLI
author: RWX
branding:
  icon: database
  color: green
runs:
  using: node16
  main: dist/index.js
inputs:
  access-token:
    description: |
      RWX Access Token.
      See https://www.rwx.com/docs/access-tokens
    required: true
  release-channel:
    description: |
      ABQ Release Channel.
    required: false
    default: v1
  run-id:
    deprecationMessage: "This is no longer used and can be safely removed from your action usage."
