name: Set up ABQ
description: Installs the ABQ CLI
author: RWX
branding:
  icon: database
  color: green
runs:
  using: node16
  main: dist/index.js
inputs:
  abq-token:
    description: |
      Deprecated ABQ API token.
    required: false
  access-token:
    description: |
      RWX Access Token.
      See https://www.rwx.com/docs/access-tokens
    required: false
