name: Continuous Integration
on:
  push:
jobs:
  test_default_version:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          access-token: ${{ secrets.RWX_ACCESS_TOKEN }}
      - run: abq --version | grep '^abq 1\.'
