name: Continuous Integration
on:
  push:
jobs:
  test-dist-checked-in:
    name: Test that build passes & updated dist/index.js is checked in
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            keep-derivations = true
            keep-outputs = true
      - run: |
          nix develop --command npm clean-install
          nix develop --command npm run build-check

  test_default_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          access-token: ${{ secrets.RWX_ACCESS_TOKEN }}
      - run: abq --version | grep '^abq 1\.'

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            keep-derivations = true
            keep-outputs = true
      - run: nix develop --command npm clean-install
      - run: nix develop --command npm run lint-check
      - run: nix fmt -- --check flake.nix
